test

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -11,87 +11,86 @@ on:
 jobs:
   build_and_deploy:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
-        tags: true
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          tags: true
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-        cache: maven
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: maven
 
-    - name: Install Maven 3.9.2
-      run: |
-        MAVEN_VERSION=3.9.2
-        wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
-        tar -xvzf apache-maven-$MAVEN_VERSION-bin.tar.gz
-        sudo mv apache-maven-$MAVEN_VERSION /opt/maven
-        sudo update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 100
-        mvn -v
+      - name: Install Maven 3.9.2
+        run: |
+          MAVEN_VERSION=3.9.2
+          wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
+          tar -xvzf apache-maven-$MAVEN_VERSION-bin.tar.gz
+          sudo mv apache-maven-$MAVEN_VERSION /opt/maven
+          sudo update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 100
+          mvn -v
 
-    - name: Cache Maven dependencies
-      uses: actions/cache@v3
-      with:
-        path: ~/.m2/repository
-        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-maven-
+      - name: Cache Maven dependencies
+        uses: actions/cache@v3
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
 
-    - name: Determine new version
-      id: version
-      run: |
-        BASE_VERSION="1.0"
-        PATCH=0
-        while true; do
-          NEW_VERSION="${BASE_VERSION}.${PATCH}"
-          if git tag -l | grep -q "^${NEW_VERSION}$"; then
-            PATCH=$((PATCH + 1))
+      - name: Determine new version
+        id: version
+        run: |
+          BASE_VERSION="1.0"
+          PATCH=0
+          while true; do
+            NEW_VERSION="${BASE_VERSION}.${PATCH}"
+            if git tag -l | grep -q "^${NEW_VERSION}$"; then
+              PATCH=$((PATCH + 1))
+            else
+              break
+            fi
+          done
+          echo "New version: $NEW_VERSION"
+          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
+
+      - name: Tag the new version
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git tag ${{ env.VERSION }}
+          git push origin ${{ env.VERSION }}
+
+      - name: OWASP Dependency-Check
+        run: |
+          curl -sSfL https://get.owasp.org/dependency-check | bash -s -- --project "MyProject" --scan . --format "ALL" --out .
+          if grep -q "CRITICAL" dependency-check-report.html; then
+            echo "Critical vulnerabilities found, failing the pipeline."
+            exit 1
           else
-            break
+            echo "No critical vulnerabilities found."
           fi
-        done
-        echo "New version: $NEW_VERSION"
-        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
 
-    - name: Tag the new version
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: |
-        git config --global user.name "github-actions[bot]"
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git tag ${{ env.VERSION }}
-        git push origin ${{ env.VERSION }}
+      - name: Build with Maven
+        run: mvn -B package --file pom.xml
 
-    - name: Build with Maven
-      run: mvn -B package --file pom.xml
+      - name: Build Docker image
+        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.VERSION }} .
 
-    - name: Build Docker image
-      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.VERSION }} .
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
-
-    - name: Push Docker image to Docker Hub
-      run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.VERSION }}
-
-    - name: OWASP Dependency-Check
-      run: |
-        curl -sSfL https://get.owasp.org/dependency-check | bash -s -- --project "MyProject" --scan . --format "ALL" --out .
-        if grep -q "CRITICAL" dependency-check-report.html; then
-          echo "Critical vulnerabilities found, failing the pipeline."
-          exit 1
-        else
-          echo "No critical vulnerabilities found."
-        fi
+      - name: Push Docker image to Docker Hub
+        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:${{ env.VERSION }}
 
   secret_scanning:
     runs-on: ubuntu-latest
